- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - name: Include user tasks
      import_tasks: tasks/users.yml

    - name: Include cron tasks
      import_tasks: tasks/cron.yml

    - name: Include package tasks
      import_tasks: tasks/packages.yml
